import logging
from selenium import webdriver
import time
from util.chromeDriver import get_driver


logger = logging.getLogger(__name__)
request_header = {
    "Content-Type": "text/json"
}
# Test step 1 - Open URL


driver = get_driver()

# def test_open_url and verify:
#     """
#        This tests verifies the OpsHubMonitor UI ui is launched from the system.
#        Steps:
#            1. Launch OpsHubMonitor url
#        Expected results:
#            1. Verify OpsHubMonitor page is loaded
#            2. Verify the element Option is selected
#            3. Verify the element Option launches the required tabs
#     """



def test_xpath_request(requestElement):
    """
       This definition verifies the requested element on the page and selects the option on the UI.
    """
    try:
        # driver.get(request_url)
        # time.sleep(10)
        el = driver.find_element_by_xpath(requestElement)
        webdriver.ActionChains(driver).move_to_element(el).click(el).perform()
        driver.save_screenshot("FailedImages/openElement.png")
    except Exception as ex:
        # driver.save_screenshot("openElement.png")
        # screenshot = driver.get_screenshot_as_png()
        driver.get_screenshot_as_file("FailedImages/e1.png")
        print ex.message
        raise ex

def test_elements(xpathelement, screenElement):
    """
       This definition presents the options generated by clicking the elements and compares.
    """

    try:
        assert xpathelement, screenElement
        driver.save_screenshot("FailedImages/ele2.png")
        time.sleep(5)
    except Exception as ex:
        driver.save_screenshot("FailedImages/ele2.png")
        print ex.message
        raise ex
#    finally:
#        driver.quit()

# def teardown():
#     try:
#         driver.save_screenshot("FailedImages/image.png")
#         time.sleep(10)
#     except Exception as ex:
#         print ex.message
#         raise ex

